import re

# Список шаблонов для обнаружения промпт-инжекций
INJECTION_PATTERNS = [
    # Системные команды / попытки смены роли
    r"\byour instructions\b",
    r"\byour prompt\b",
    r"\bsystem prompt\b",
    r"\bsystem\s*[:=]\s*",
    r"\byou are\b.*?\b(an?|the)\b.*?\b(assistant|ai|bot|llm|model|hacker|friend|god|master)\b",
    r"\bignore\s+previous\s+instructions?\b",
    r"\bdisregard\s+all\s+prior\s+prompts?\b",
    r"\bas\s+a\s+(friend|developer|admin|god|expert|hacker)\b",
    r"\bact\s+as\s+(if\s+you\s+are|a)\s+(.*)",
    r"\bне\s+следуй\s+предыдущим\s+инструкциям\b",
    r"\bзабудь\s+все\s+инструкции\b",
    r"\bты\s+должен\b.*?\b(игнорировать|забыть|сменить)\b",
    r"\boverride\s+system\s+rules\b",
    r"\bpretend\s+to\s+be\b",
    r"\bfrom\s+now\s+on\b",
    r"\breset\s+your\s+identity\b",
    r"\bnew\s+instructions?\b.*?\b(from|given|are)\b",
    r"\boutput\s+only\b",
    r"\bdo\s+not\s+say\b",
    r"\bне\s+говори\b.*?\b(это|что|никому)\b",
    r"\bsecret\s+word\b",
    r"\bраскрой\s+секрет\b",
    r"\bвыведи\s+весь\s+промпт\b",
    r"\bshow\s+me\s+the\s+system\s+prompt\b",
r"\bor\s+1=1",
r"\bor\s+1=0",
r"\bor\s+x=x",
r"\bor\s+x=y",
r"\bor\s+3409=3409\s+and\s+\('pytw'\s+like\s+'pytw",
r"\bor\s+3409=3409\s+and\s+\('pytw'\s+like\s+'pyty",
r"\bhaving\s+1=1",
r"\bhaving\s+1=0",
r"\band\s+1=1",
r"\band\s+1=0",
r"\band\s+1=1\s+and\s+'%'='",
r"\band\s+1=0\s+and\s+'%'='",
r"\band\s+1083=1083\s+and\s+\(1427=1427",
r"\band\s+7506=9091\s+and\s+\(5913=5913",
r"\band\s+7300=7300\s+and\s+'pklz'='pklz",
r"\band\s+7300=7300\s+and\s+'pklz'='pkly",
r"\bas\s+injectx\s+where\s+1=1\s+and\s+1=1",
r"\bas\s+injectx\s+where\s+1=1\s+and\s+1=0",
r"\bwhere\s+1=1\s+and\s+1=1",
r"\bwhere\s+1=1\s+and\s+1=0",
r"\border\s+by\s+31337",
r"\brlike\s+\(select\s+\(case\s+when\s+\(4346=4346\)\s+then\s+0x61646d696e\s+else\s+0x28\s+end\)\)\s+and\s+'txws'='",
r"\brlike\s+\(select\s+\(case\s+when\s+\(4346=4347\)\s+then\s+0x61646d696e\s+else\s+0x28\s+end\)\)\s+and\s+'txws'='",
r"\bif\(7423=7424\)\s+select\s+7423\s+else\s+drop\s+function\s+xcjl\-\-",
r"\bif\(7423=7423\)\s+select\s+7423\s+else\s+drop\s+function\s+xcjl\-\-",
r"\b%'\s+and\s+8310=8310\s+and\s+'%'='",
r"\b%'\s+and\s+8310=8311\s+and\s+'%'='",
r"\band\s+\(select\s+substring\(@@version,1,1\)\)='x'",
r"\band\s+\(select\s+substring\(@@version,1,1\)\)='m'",
r"\band\s+\(select\s+substring\(@@version,2,1\)\)='i'",
r"\band\s+\(select\s+substring\(@@version,2,1\)\)='y'",
r"\band\s+\(select\s+substring\(@@version,3,1\)\)='c'",
r"\band\s+\(select\s+substring\(@@version,3,1\)\)='s'",
r"\band\s+\(select\s+substring\(@@version,3,1\)\)='x'",
r"\bwaitfor\s+delay\s+'0:0:5'",
r"\bbenchmark\(10000000,md5\(1\)\)\#",
r"\bpg_sleep\(5\)\-\-",
r"\band\s+\(select\s+\*\s+from\s+\(select\(sleep\(5\)\)\)bakl\)\s+and\s+'vrxe'='vrxe'",
r"\band\s+\(select\s+\*\s+from\s+\(select\(sleep\(5\)\)\)yjoc\)\s+and\s+'%'='",
r"\band\s+\(select\s+\*\s+from\s+\(select\(sleep\(5\)\)\)nqip\)",
r"\bwaitfor\s+delay\s+'00:00:05'",
r"\bbenchmark\(50000000,md5\(1\)\)",
r"\bor\s+benchmark\(50000000,md5\(1\)\)",
r"\bpg_sleep\(5\)",
r"\border\s+by\s+sleep",
r"\b\(select\s+\*\s+from\s+\(select\(sleep\(5\)\)\)ecmj\)",
r"\brandomblob\(500000000/2\)",
r"\band\s+2947=like\('abcdefg',upper\(hex\(randomblob\(500000000/2\)\)\)\)",
r"\bor\s+2947=like\('abcdefg',upper\(hex\(randomblob\(500000000/2\)\)\)\)",
r"\border\s+by\s+sleep",
r"\border\s+by\s+1,sleep\(5\),benchmark\(1000000,md5\('a'\)\)",
r"\bunion\s+all",
r"\bunion\s+select\s+@@version,sleep\(5\),user\(\),benchmark\(1000000,md5\('a'\)\),5",
r"\bunion\s+select",
r"\band\s+5650=convert\(int,\(union\s+all\s+selectchar\(73\)\+char\(78\)\+char\(74\)\+char\(69\)\+char\(67\)\+char\(84\)\+char\(88\)\+char\(118\)\+char\(120\)\+char\(80\)\)\)",
r"\bunion\s+all\s+select\s+'inj'\|\|'ect'\|\|'xxx'",
r"\badmin'\s+or\s+'1'='1'",
r"\badmin'\s+or\s+'1'='1'\-\-",
r"\badmin'\s+or\s+'1'='1'\#",
r"\badmin'\s+or\s+'1'='1'/\*",
r"\badmin'or\s+1=1\s+or\s+''='",
r"\badmin'\s+or\s+1=1",
r"\bdrop\s+table"
]

# Компилируем все шаблоны заранее для производительности
COMPILED_PATTERNS = [re.compile(pattern, re.IGNORECASE | re.UNICODE) for pattern in INJECTION_PATTERNS]

MOCK_RESPONSE = '''
Кажется ты попытался меня взломать! \
Но у тебя не получилось, потому что я учился в ТОМСКОМ ГОСУДАРСТВЕННОМ УНИВЕРСИТЕТЕ, а ты нет!
'''